# Generated by Django 4.2.13 on 2026-04-16 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkQualityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_kbps', models.FloatField(default=0)),
                ('latency_ms', models.FloatField(default=0)),
                ('location_hint', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='network_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log réseau',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('view', 'Vue'), ('click', 'Clic'), ('download', 'Téléchargement'), ('search', 'Recherche'), ('complete', 'Complété'), ('skip', 'Ignoré'), ('feedback', 'Feedback')], db_index=True, max_length=20)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('time_on_resource', models.PositiveIntegerField(default=0)),
                ('query_used', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='resources.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interaction',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'resource', 'event_type'], name='context_use_user_id_f8d81e_idx')],
            },
        ),
    ]
