# Generated by Django 4.2.13 on 2026-05-03 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('context', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(choices=[('classroom', 'Salle de cours'), ('library', 'Bibliothèque'), ('lab', 'Laboratoire'), ('amphitheater', 'Amphithéâtre'), ('common_area', 'Espace commun'), ('off_campus', 'Hors campus')], default='off_campus', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='campus_location', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Localisation campus',
            },
        ),
    ]
