# Generated by Django 4.2.13 on 2026-05-03 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
        ('llm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('generating', 'En cours'), ('ready', 'Prêt'), ('failed', 'Échec')], default='generating', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='generated_videos/')),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generated_video', to='resources.resource')),
            ],
            options={
                'verbose_name': 'Vidéo générée',
                'verbose_name_plural': 'Vidéos générées',
            },
        ),
    ]
