# Generated by Django 4.2.13 on 2026-05-03 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
        ('llm', '0002_generatedvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedvideo',
            name='level',
            field=models.CharField(default='beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='generatedvideo',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_videos', to='resources.resource'),
        ),
        migrations.AlterUniqueTogether(
            name='generatedvideo',
            unique_together={('resource', 'level')},
        ),
    ]
