# Generated by Django 4.2.13 on 2026-04-16 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('external_url', models.URLField(blank=True)),
                ('level', models.CharField(choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('advanced', 'Avancé')], db_index=True, default='beginner', max_length=20)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('video', 'Vidéo'), ('audio', 'Audio'), ('html', 'Page Web'), ('image', 'Image'), ('zip', 'Archive'), ('other', 'Autre')], db_index=True, default='pdf', max_length=20)),
                ('language', models.CharField(choices=[('fr', 'Français'), ('ar', 'Arabe'), ('en', 'Anglais')], default='fr', max_length=5)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('dcat_identifier', models.CharField(blank=True, max_length=255)),
                ('dcat_publisher', models.CharField(blank=True, max_length=255)),
                ('dcat_license', models.CharField(blank=True, max_length=255)),
                ('dcat_issued', models.DateField(blank=True, null=True)),
                ('dcat_modified', models.DateField(blank=True, null=True)),
                ('dcat_keywords', models.JSONField(blank=True, default=list)),
                ('is_validated', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('average_rating', models.FloatField(default=0.0)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='resources.category')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ressource',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['level', 'format', 'language'], name='resources_r_level_9ca892_idx'), models.Index(fields=['is_validated', 'is_active'], name='resources_r_is_vali_9cb807_idx')],
            },
        ),
    ]
